version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
  # Node api service
  api:
    build: ./Dockerfile
    ports:
      # local->container
      - 3030:3030
    environment:
      PORT: 3030
      MONGODB_URI: mongodb://mongo_db:27017/mydb
    depends_on:
      - mongo_db
    networks:
      - my-network
volumes:
  mongo_data: {}

networks:
  my-network:
    driver: bridge
