version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017/mydb
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
